name: build

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.14.x
      id: go

    - uses: actions/checkout@v1

    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Test
      run: go test -v -coverprofile coverage.txt -covermode atomic ./...

    # - uses: codecov/codecov-action@v1.0.0
    #   with:
    #     token: ${{secrets.CODECOV_TOKEN}}
    #     file: ./coverage.txt
